spring:
  application:
    name: coin-analyzer
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 30000
  jackson:
    time-zone: UTC
logging:
  level:
    com.creda.coin.price: INFO
    org.mybatis.spring: ERROR
    org.apache.ibatis: ERROR
    com.zaxxer.hikari: ERROR
    org.elasticsearch.client.RestClient: ERROR

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.creda.coin.price.entity


candles:
  intervals: "15, 30, 60, 240, 1440"

job:
  enabled: true

SENTRY_AUTH_TOKEN: 1111

kafka:
  send:
    limit: 3000