spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:9030/solana?useSSL=false&serverTimezone=Asia/Chongqing
    username: root
    password:
    hikari:
      maximum-pool-size: 20  # 最大连接数
      minimum-idle: 5        # 最小空闲连接数
      idle-timeout: 30000    # 空闲连接的最大存活时间，单位：毫秒
      connection-timeout: 30000 # 获取连接的最大等待时间，单位：毫秒
      max-lifetime: 600000   # 连接池中连接的最大生命周期，单位：毫秒
  elasticsearch:
    rest:
      uris: http://localhost:9001
      username: test1
      password: D6XCYYf55KaVgiUxb

  kafka:
    bootstrap-servers: localhost:9092 # Kafka 集群地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      max-request-size: 20971520
      buffer-memory: 209715200
      batch-size: 2097152

# application.yml
doris:
  stream-load:
    url: http://127.0.0.1:8030/api/{database}/{table}/_stream_load
    username: root
    password:
    database: solana

es:
  search:
    limit: 50

server:
  port: 8111
